### PR TITLE
fix wrong behavior in symbolic link folder.

### PR DESCRIPTION
**Pull request by tttuuu888**
fix for issue #278 
I got a hint from ggtags.

Thanks a lot for this great package.

### CODE REVIEW

**Comment by palikar** [comment]
Hi @tttuuu888 , thanks for bringing attention to this issue! Your fix, however, doesn't really fix it as per definition the function should also check the subdirectories recursively. I've fixed the bug now (ee3f508f8cc854c96e7845e5ccbd86cf88cbbfe7). Again, thanks for the feedback!

**Comment by tttuuu888** [comment]
@palikar Oh right.. I was too focused on my issue so didn't even check the function definition and description in detail. I am sorry for this. 

However it looks like this fix is even making 'neotree-select-up-node' working more weird. Now when I push 'u' to execute 'neotree-select-up-node', emacs stops for a while and root directory is changed. Please check it. (tested with 'neotree-20181120.2232')

In addition, 'neo-path--file-in-directory-p' function itself is working as expected with this fix. But I've just tested previous version of 'neo-path--file-in-directory-p' and I figured out it was also working fine even with symbolic link folder.

Thanks for your fix for this issue and thanks for this package again!

**Comment by palikar** [comment]
Hi @tttuuu888, yep, similar issues were expressed in #310. Right now I am wondering what should I do as I am testing stuff and even the function `file-in-directory-p` itself is behaving kind of strange, not reporting proper results from time time. Most probably, I will just revert the change.

**Comment by palikar** [comment]
Ok, I've reverted the change. Can you guys let me know if now the things are as before?

As said, I've tested the function in question and I don't think is behaves aboslutely correctly in 100% of the cases (at least for me, for @tttuuu888 it seems to work). Either way, I think we could say that before the change the function was "good enough" for neotree. Let me know if you encounter some issues that has to do with opening projects with symlink or that have symlink folders inside of the.

**Comment by amasover** [comment]
@palikar Yes, I've tested after your latest commit and everything seems to work great, as before. Thanks!

**Pull request closed without merging**
