### PR TITLE
Indent as Vim-NERDTree

### PR DESCRIPTION
**Pull request by hbin**
Hi, thanks for your effort to develop this package. Awesome!
Actually, I use both Vim and Emacs everyday ;) This is one of the best features that why I insist on Vim.

I've been use this package for a while. And I customise it in my favor.

This PR set the indentation as Vim-NERDTree.

### CODE REVIEW

**Comment by jaypei** [comment]
Hi hbin,

Thanks for your improvements!
I tried this PR, it looks a wrong indentation ("bin" and "LICENSE" is the same level).



jaypei

**Comment by jaypei** [comment]
Recently, neotree make a new identation style,
https://github.com/jaypei/emacs-neotree/pull/86

**Comment by hbin** [comment]
I forgot to place a `blank space` between the fold-symbols and nodes. I have done that in another [PR](https://github.com/jaypei/emacs-neotree/pull/79.)
Sorry about disturb you.

Here a comparison between Emacs and Vim.
image
image

**Comment by jaypei** [comment]
Hi hbin,

This is the old implementation, but this issue has proved that it is not a good implementation:
https://github.com/jaypei/emacs-neotree/pull/68

I think many peoples are already used to the NerdTree indentation, we can add a new theme "nerd-ascii",
and users can customize with their preferences.

Do you agree with that?

jaypei

**Comment by hbin** [comment]
Fair enough. Thank you pei.

**Comment by jaypei** [comment]
Hi hbin,
I already added the NerdTree theme, is that your want?


Jaypei

**Comment by hbin** [comment]
Thank you for your effort.

**Pull request closed without merging**
