### PR TITLE
Add support for `nerd-icons`

### PR DESCRIPTION
**Pull request by abougouffa**
Hello!

First, let me thank you for this package!

This PR adds support for [`nerd-icons`](https://github.com/rainstormstudio/nerd-icons.el) in the same way `neotree` supports `all-the-icons` for now.

### CODE REVIEW

**Comment by abougouffa** [comment]
ping @jaypei

**Comment by toyboot4e** [comment]
Love this PR! Can you remove `display-graphics-p` so that it works on terminal, too?

**Comment by abougouffa** [comment]
@toyboot4e Thanks for the feedback, I've pushed the suggested change!

**Comment by Abdisalan** [comment]
Thanks for the update! Works and looks great in GUI and terminal 👍🏾

**Comment by azzamsa** [comment]
Thanks a lot for this, [abougouffa](https://github.com/abougouffa). This is the only package left in my system that relies on `all-the-icons`.

**Pull request merged**
